package OgmaOATSParser;

/* The following code was generated by JFlex 1.4.3 on 10/12/15 08:55 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/12/15 08:55 from the specification file
 * <tt>oatsl.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRINGSTATE = 4;
  public static final int IMPORTSTATE = 6;
  public static final int JAVADOCSTATE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  3,  0,  0,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0, 33,  0,  0,  0,  0,  0, 27, 27, 29,  0, 27,  0, 27, 32, 
    30, 30, 30, 30, 30, 30, 30, 30, 30, 30,  0, 28,  0,  0,  0,  0, 
    20, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 
    31, 31, 31, 21, 31, 31, 31, 31, 31, 31, 31,  0,  0,  0,  0,  0, 
     0, 14, 11, 13, 19, 16, 31, 26, 23,  4, 31, 25, 12,  5, 18,  7, 
     6, 31,  8, 15,  9, 10, 22, 24, 17, 31, 31, 27,  0, 27,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\2\4\7\5\1\3\1\5"+
    "\1\6\1\7\1\3\1\10\3\1\2\4\1\11\1\2"+
    "\1\4\7\5\1\0\1\5\1\0\1\12\1\4\10\5"+
    "\1\0\1\5\1\13\10\5\1\0\1\14\2\5\1\15"+
    "\2\5\1\16\2\5\1\0\1\17\1\20\1\21\3\5"+
    "\1\0\1\5\1\22\1\23\1\0\1\5\1\0\1\24"+
    "\5\0\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe"+
    "\0\210\0\u0220\0\u0242\0\210\0\210\0\u0264\0\u0286\0\u02a8"+
    "\0\u02ca\0\210\0\u02ec\0\210\0\u030e\0\u0330\0\u0352\0\u0374"+
    "\0\u0396\0\u03b8\0\u03da\0\u03fc\0\u041e\0\u0440\0\210\0\u0286"+
    "\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\u050c\0\u052e\0\u0550"+
    "\0\u0572\0\u0594\0\210\0\u05b6\0\u05d8\0\u05fa\0\u061c\0\u063e"+
    "\0\u0660\0\u0682\0\u06a4\0\u06c6\0\u0110\0\u06e8\0\u070a\0\u0110"+
    "\0\u072c\0\u074e\0\u0110\0\u0770\0\u0792\0\u07b4\0\u0110\0\u0110"+
    "\0\u0110\0\u07d6\0\u07f8\0\u081a\0\u083c\0\u085e\0\u0110\0\u0110"+
    "\0\u0880\0\u08a2\0\u08c4\0\u0110\0\u08e6\0\u0908\0\u092a\0\u094c"+
    "\0\u096e\0\210";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\6\1\10\1\11\1\12\2\11"+
    "\1\13\1\11\1\14\1\11\1\15\2\11\1\16\3\11"+
    "\1\17\1\11\1\20\4\11\3\21\1\22\1\11\1\23"+
    "\1\24\1\25\1\6\1\7\1\6\31\25\1\26\4\25"+
    "\1\27\1\30\1\31\1\30\35\27\1\32\1\33\1\6"+
    "\1\7\1\6\30\33\1\32\5\33\43\0\1\6\1\0"+
    "\1\6\41\0\1\34\42\0\1\11\1\35\16\11\1\0"+
    "\6\11\3\0\2\11\6\0\20\11\1\0\6\11\3\0"+
    "\2\11\6\0\6\11\1\36\11\11\1\0\6\11\3\0"+
    "\2\11\6\0\20\11\1\0\2\11\1\37\3\11\3\0"+
    "\2\11\6\0\14\11\1\40\3\11\1\0\6\11\3\0"+
    "\2\11\6\0\10\11\1\41\7\11\1\0\6\11\3\0"+
    "\2\11\6\0\15\11\1\42\1\43\1\11\1\0\6\11"+
    "\3\0\2\11\27\0\1\44\20\0\3\11\1\45\14\11"+
    "\1\0\6\11\3\0\2\11\6\0\20\11\1\0\6\11"+
    "\3\0\1\22\1\11\37\0\1\46\44\0\1\47\1\0"+
    "\41\27\1\0\1\27\1\30\1\27\1\30\35\27\1\0"+
    "\3\27\1\50\35\27\1\0\1\33\3\0\30\33\1\0"+
    "\5\33\4\0\2\11\1\51\15\11\1\0\6\11\3\0"+
    "\2\11\6\0\7\11\1\52\10\11\1\0\6\11\3\0"+
    "\2\11\6\0\1\53\3\11\1\54\13\11\1\0\6\11"+
    "\3\0\2\11\6\0\20\11\1\0\5\11\1\55\3\0"+
    "\2\11\6\0\12\11\1\56\5\11\1\0\6\11\3\0"+
    "\2\11\6\0\5\11\1\57\12\11\1\0\6\11\3\0"+
    "\2\11\6\0\17\11\1\60\1\0\6\11\3\0\2\11"+
    "\17\0\1\61\30\0\1\62\17\11\1\0\6\11\3\0"+
    "\2\11\37\0\1\63\10\0\3\11\1\64\14\11\1\0"+
    "\6\11\3\0\2\11\6\0\10\11\1\65\7\11\1\0"+
    "\6\11\3\0\2\11\6\0\16\11\1\66\1\11\1\0"+
    "\6\11\3\0\2\11\6\0\3\11\1\67\14\11\1\0"+
    "\6\11\3\0\2\11\6\0\1\70\17\11\1\0\6\11"+
    "\3\0\2\11\6\0\13\11\1\71\4\11\1\0\6\11"+
    "\3\0\2\11\6\0\14\11\1\72\3\11\1\0\6\11"+
    "\3\0\2\11\6\0\20\11\1\0\1\73\5\11\3\0"+
    "\2\11\12\0\1\74\35\0\17\11\1\75\1\0\6\11"+
    "\3\0\2\11\6\0\4\11\1\76\13\11\1\0\6\11"+
    "\3\0\2\11\6\0\1\77\17\11\1\0\6\11\3\0"+
    "\2\11\6\0\20\11\1\0\4\11\1\100\1\11\3\0"+
    "\2\11\6\0\20\11\1\0\3\11\1\101\2\11\3\0"+
    "\2\11\6\0\16\11\1\102\1\11\1\0\6\11\3\0"+
    "\2\11\6\0\13\11\1\103\4\11\1\0\6\11\3\0"+
    "\2\11\6\0\16\11\1\104\1\11\1\0\6\11\3\0"+
    "\2\11\6\0\5\11\1\105\12\11\1\0\6\11\3\0"+
    "\2\11\6\0\1\106\41\0\5\11\1\107\12\11\1\0"+
    "\6\11\3\0\2\11\6\0\11\11\1\110\6\11\1\0"+
    "\6\11\3\0\2\11\6\0\13\11\1\111\4\11\1\0"+
    "\6\11\3\0\2\11\6\0\20\11\1\0\1\112\5\11"+
    "\3\0\2\11\6\0\17\11\1\113\1\0\6\11\3\0"+
    "\2\11\6\0\14\11\1\114\3\11\1\0\6\11\3\0"+
    "\2\11\10\0\1\115\37\0\5\11\1\116\12\11\1\0"+
    "\6\11\3\0\2\11\6\0\13\11\1\117\4\11\1\0"+
    "\6\11\3\0\2\11\6\0\2\11\1\120\15\11\1\0"+
    "\6\11\3\0\2\11\13\0\1\121\34\0\14\11\1\122"+
    "\3\11\1\0\6\11\3\0\2\11\27\0\1\123\20\0"+
    "\2\11\1\124\15\11\1\0\6\11\3\0\2\11\22\0"+
    "\1\125\31\0\1\126\57\0\1\127\17\0\1\130\52\0"+
    "\1\131\44\0\1\132\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2448];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\1\1\11\13\1\1\11\2\1\2\11\4\1"+
    "\1\11\1\1\1\11\7\1\1\0\1\1\1\0\1\11"+
    "\11\1\1\0\1\1\1\11\10\1\1\0\11\1\1\0"+
    "\6\1\1\0\3\1\1\0\1\1\1\0\1\1\5\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Parser yyparser;

	public Yylex (java.io.Reader r, Parser yyparser)
	{
		this(r);
		this.yyparser = yyparser;
		yyline = 1;
	}

	public int getLine()
	{
		return yyline;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { yybegin(YYINITIAL); return (int) yycharat(0);
          }
        case 22: break;
        case 10: 
          { yybegin(YYINITIAL); return Parser.JAVADOCEND;
          }
        case 23: break;
        case 7: 
          { return Parser.NUMBER;
          }
        case 24: break;
        case 14: 
          { return Parser.CLASS;
          }
        case 25: break;
        case 18: 
          { return Parser.EXTENDS;
          }
        case 26: break;
        case 6: 
          { return (int) yycharat(0);
          }
        case 27: break;
        case 20: 
          { return Parser.BEGINSTEP;
          }
        case 28: break;
        case 15: 
          { yybegin(IMPORTSTATE); return Parser.IMPORT;
          }
        case 29: break;
        case 16: 
          { return Parser.PUBLIC;
          }
        case 30: break;
        case 2: 
          { yyparser.yylval = new ParserVal(yytext());
								 	  return Parser.ANY;
          }
        case 31: break;
        case 17: 
          { return Parser.THROWS;
          }
        case 32: break;
        case 21: 
          { yybegin(IMPORTSTATE); return Parser.SCRIPTSERVICE;
          }
        case 33: break;
        case 11: 
          { yybegin(JAVADOCSTATE); return Parser.JAVADOCSTART;
          }
        case 34: break;
        case 12: 
          { return Parser.VOID;
          }
        case 35: break;
        case 13: 
          { return Parser.THINK;
          }
        case 36: break;
        case 5: 
          { yyparser.yylval = new ParserVal(yytext());
				  return Parser.IDENTIFIER;
          }
        case 37: break;
        case 8: 
          { yybegin(STRINGSTATE); return (int) yycharat(0);
          }
        case 38: break;
        case 3: 
          { return Parser.UNKNOWN;
          }
        case 39: break;
        case 1: 
          { yyparser.yylval = new ParserVal(yytext());
						  return Parser.ANY;
          }
        case 40: break;
        case 19: 
          { return Parser.ENDSTEP;
          }
        case 41: break;
        case 4: 
          { 
          }
        case 42: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
