/*
SCRIPT AUTOMATICALLY GENERATED BY PLETS v1.1.5
*/

import oracle.oats.scripting.modules.basic.api.*;
import oracle.oats.scripting.modules.browser.api.*;
import oracle.oats.scripting.modules.functionalTest.api.*;
import oracle.oats.scripting.modules.utilities.api.*;
import oracle.oats.scripting.modules.utilities.api.sql.*;
import oracle.oats.scripting.modules.utilities.api.xml.*;
import oracle.oats.scripting.modules.utilities.api.file.*;
import oracle.oats.scripting.modules.webdom.api.*;
import oracle.oats.scripting.modules.formsFT.api.*;
import oracle.oats.scripting.modules.applet.api.*;

public class script extends IteratingVUserScript {
	@ScriptService oracle.oats.scripting.modules.utilities.api.UtilitiesService utilities;
	@ScriptService oracle.oats.scripting.modules.browser.api.BrowserService browser;
	@ScriptService oracle.oats.scripting.modules.functionalTest.api.FunctionalTestService ft;
	@ScriptService oracle.oats.scripting.modules.webdom.api.WebDomService web;
	@ScriptService oracle.oats.scripting.modules.applet.api.AppletService applet;
	@ScriptService oracle.oats.scripting.modules.formsFT.api.FormsService forms;

	public void initialize() throws Exception {
		browser.closeAllBrowsers();
		browser.launch();
	}

	public void run() throws Exception {
		beginStep("InitialNode", 1);
		{
			.window(1, "{{obj..web_window_0}}").waitForPage();
			{
				think(1);
			}
			beginStep("[1.1]Moodle(/moodle/)", 3);
			{

			}
			endStep();
			beginStep("[1.2] Moodle(/moodle/)", 4);
			{
				.link(4, "{{obj..web_a_Login_here_}}").wait(dt_WaitTimeLong},{click},{wait, dt_WaitTimeLong},{existstimeout, true, dt_ObjectTimeOut);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.1] Moodle: Login to the site(/login/)", 6);
			{
				.window(6, "{{obj..web_window_0_1}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.2] Moodle: Login to the site(/login/)", 8);
			{
				.Invalid(8, "{{obj..web_input_text_username}}").click},{set(dt_username},{pressTab);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.3] Moodle: Login to the site(/login/)", 10);
			{
				.Invalid(10, "{{obj..web_input_password_password}}").set(dt_password);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.4] Moodle: Login to the site(/login/)", 12);
			{
				.button(12, "{{obj..web_input_submit_liginbtn}}").wait(dt_WaitTimeShort},{click);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[3,1]Moodle(/moodle/)", 14);
			{
				.window(14, "{{obj..web_window_0}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[3,2]Moodle(/moodle/)", 16);
			{
				.link(16, "{{obj..web_a_My_courses}}").existstimeout(true, dt_ObjectTimeOut},{click);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[4.1] My moodle:My home(/my/)", 18);
			{
				.window(18, "{{obj..web_window_0_2}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[4.2] My moodle:My home(/my/)", 20);
			{
				.link(20, "{{obj..web_a_Functional_Testing}}").existstimeout(true, dt_ObjectTimeOut},{click);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[5.1] Course: Functional Testing(/ view.php)", 22);
			{
				.window(22, "{{obj..web_window_0_3}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[5.2] Course: Functional Testing(/ view.php)", 24);
			{
				.link(24, "{{obj..web_a_Logout}}").click();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[6]Moodle(/moodle/)", 26);
			{
				.window(26, "{{obj..web_window_0}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();

		}
		endStep();

	}
	public void finish() throws Exception {
	}
}
