/*
SCRIPT AUTOMATICALLY GENERATED BY PLETS v1.1.5
*/

import oracle.oats.scripting.modules.basic.api.*;
import oracle.oats.scripting.modules.browser.api.*;
import oracle.oats.scripting.modules.functionalTest.api.*;
import oracle.oats.scripting.modules.utilities.api.*;
import oracle.oats.scripting.modules.utilities.api.sql.*;
import oracle.oats.scripting.modules.utilities.api.xml.*;
import oracle.oats.scripting.modules.utilities.api.file.*;
import oracle.oats.scripting.modules.webdom.api.*;
import oracle.oats.scripting.modules.formsFT.api.*;
import oracle.oats.scripting.modules.applet.api.*;

public class script extends IteratingVUserScript {
	@ScriptService oracle.oats.scripting.modules.utilities.api.UtilitiesService utilities;
	@ScriptService oracle.oats.scripting.modules.browser.api.BrowserService browser;
	@ScriptService oracle.oats.scripting.modules.functionalTest.api.FunctionalTestService ft;
	@ScriptService oracle.oats.scripting.modules.webdom.api.WebDomService web;
	@ScriptService oracle.oats.scripting.modules.applet.api.AppletService applet;
	@ScriptService oracle.oats.scripting.modules.formsFT.api.FormsService forms;

	public void initialize() throws Exception {
		browser.closeAllBrowsers();
		browser.launch();
	}

	public void run() throws Exception {
		beginStep("InitialNode", 1);
		{
			.Invalid(1, "{{obj..Invalid}}").navigate(http://192.168.1.10:8080/GerenciadorPampatec/);
			{
				think(1);
			}
			beginStep("Acessar Sistema", 3);
			{

			}
			endStep();
			beginStep("Informar dados", 4);
			{
				.Invalid(4, "{{obj..Invalid}}").waitForPage(http://192.168.1.10:8080/GerenciadorPampatec/);
				{
					think(1);
				}

			}
			endStep();
			beginStep("Autenticar dados", 6);
			{
				.Invalid(6, "{{obj..formularioDeLogin:emailInput}}").click}{set-Text(testetestezin@gmail.com}{pressTab}{set-Text, teste123);
				{
					think(1);
				}
				.Invalid(7, "{{obj..http://192.168.1.10:8080/GerenciadorPampatec/}}").click();
				{
					think(1);
				}

			}
			endStep();

		}
		endStep();

	}
	public void finish() throws Exception {
	}
}
