/*
SCRIPT AUTOMATICALLY GENERATED BY PLETS v1.1.5
*/

import oracle.oats.scripting.modules.basic.api.*;
import oracle.oats.scripting.modules.browser.api.*;
import oracle.oats.scripting.modules.functionalTest.api.*;
import oracle.oats.scripting.modules.utilities.api.*;
import oracle.oats.scripting.modules.utilities.api.sql.*;
import oracle.oats.scripting.modules.utilities.api.xml.*;
import oracle.oats.scripting.modules.utilities.api.file.*;
import oracle.oats.scripting.modules.webdom.api.*;
import oracle.oats.scripting.modules.formsFT.api.*;
import oracle.oats.scripting.modules.applet.api.*;

public class script extends IteratingVUserScript {
	@ScriptService oracle.oats.scripting.modules.utilities.api.UtilitiesService utilities;
	@ScriptService oracle.oats.scripting.modules.browser.api.BrowserService browser;
	@ScriptService oracle.oats.scripting.modules.functionalTest.api.FunctionalTestService ft;
	@ScriptService oracle.oats.scripting.modules.webdom.api.WebDomService web;
	@ScriptService oracle.oats.scripting.modules.applet.api.AppletService applet;
	@ScriptService oracle.oats.scripting.modules.formsFT.api.FormsService forms;

	public void initialize() throws Exception {
		browser.closeAllBrowsers();
		browser.launch();
	}

	public void run() throws Exception {
		beginStep("InitialNode", 1);
		{
			.window(1, "{{obj..web_window_0}}").waitForPage();
			{
				think(1);
			}
			beginStep("[1.1]Moodle(/moodle/)", 3);
			{

			}
			endStep();
			beginStep("[1.2] Moodle(/moodle/)", 4);
			{
				.link(4, "{{obj..web_a_Login_here_}}").wait(dt_WaitTimeLong);
				{
					think(1);
				}
				.link(5, "{{obj..web_a_Login_here_}}");
				{
					think(1);
				}
				.link(6, "{{obj..web_a_Login_here_}}").click();
				{
					think(1);
				}
				.link(7, "{{obj..web_a_Login_here_}}");
				{
					think(1);
				}
				.link(8, "{{obj..web_a_Login_here_}}").wait(dt_WaitTimeLong);
				{
					think(1);
				}
				.link(9, "{{obj..web_a_Login_here_}}");
				{
					think(1);
				}
				.link(10, "{{obj..web_a_Login_here_}}").existstimeout(true, dt_ObjectTimeOut);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.1] Moodle: Login to the site(/login/)", 12);
			{
				.window(12, "{{obj..web_window_0_1}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.2] Moodle: Login to the site(/login/)", 14);
			{
				.Invalid(14, "{{obj..web_input_text_username}}").click();
				{
					think(1);
				}
				.Invalid(15, "{{obj..web_input_text_username}}");
				{
					think(1);
				}
				.Invalid(16, "{{obj..web_input_text_username}}").set(dt_username);
				{
					think(1);
				}
				.Invalid(17, "{{obj..web_input_text_username}}");
				{
					think(1);
				}
				.Invalid(18, "{{obj..web_input_text_username}}").pressTab();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.3] Moodle: Login to the site(/login/)", 20);
			{
				.Invalid(20, "{{obj..web_input_password_password}}").set(dt_password);
				{
					think(1);
				}

			}
			endStep();
			beginStep("[2.4] Moodle: Login to the site(/login/)", 22);
			{
				.button(22, "{{obj..web_input_submit_liginbtn}}").wait(dt_WaitTimeShort);
				{
					think(1);
				}
				.button(23, "{{obj..web_input_submit_liginbtn}}");
				{
					think(1);
				}
				.button(24, "{{obj..web_input_submit_liginbtn}}").click();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[3,1]Moodle(/moodle/)", 26);
			{
				.window(26, "{{obj..web_window_0}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[3,2]Moodle(/moodle/)", 28);
			{
				.link(28, "{{obj..web_a_My_courses}}").existstimeout(true, dt_ObjectTimeOut);
				{
					think(1);
				}
				.link(29, "{{obj..web_a_My_courses}}");
				{
					think(1);
				}
				.link(30, "{{obj..web_a_My_courses}}").click();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[4.1] My moodle:My home(/my/)", 32);
			{
				.window(32, "{{obj..web_window_0_2}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[4.2] My moodle:My home(/my/)", 34);
			{
				.link(34, "{{obj..web_a_Functional_Testing}}").existstimeout(true, dt_ObjectTimeOut);
				{
					think(1);
				}
				.link(35, "{{obj..web_a_Functional_Testing}}");
				{
					think(1);
				}
				.link(36, "{{obj..web_a_Functional_Testing}}").click();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[5.1] Course: Functional Testing(/ view.php)", 38);
			{
				.window(38, "{{obj..web_window_0_3}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[5.2] Course: Functional Testing(/ view.php)", 40);
			{
				.link(40, "{{obj..web_a_Logout}}").click();
				{
					think(1);
				}

			}
			endStep();
			beginStep("[6]Moodle(/moodle/)", 42);
			{
				.window(42, "{{obj..web_window_0}}").waitForPage();
				{
					think(1);
				}

			}
			endStep();

		}
		endStep();

	}
	public void finish() throws Exception {
	}
}
