/*
SCRIPT AUTOMATICALLY GENERATED BY PLETS v1.1.5
*/

import oracle.oats.scripting.modules.basic.api.*;
import oracle.oats.scripting.modules.browser.api.*;
import oracle.oats.scripting.modules.functionalTest.api.*;
import oracle.oats.scripting.modules.utilities.api.*;
import oracle.oats.scripting.modules.utilities.api.sql.*;
import oracle.oats.scripting.modules.utilities.api.xml.*;
import oracle.oats.scripting.modules.utilities.api.file.*;
import oracle.oats.scripting.modules.webdom.api.*;

public class script extends IteratingVUserScript {
	@ScriptService oracle.oats.scripting.modules.utilities.api.UtilitiesService utilities;
	@ScriptService oracle.oats.scripting.modules.browser.api.BrowserService browser;
	@ScriptService oracle.oats.scripting.modules.functionalTest.api.FunctionalTestService ft;
	@ScriptService oracle.oats.scripting.modules.webdom.api.WebDomService web;

	public void initialize() throws Exception {
		browser.closeAllBrowsers();
		browser.launch();
	}

	public void run() throws Exception {
		beginStep("Acessar Sistema", 1);
		{
			web.window(1, "/web:window[@index='0']"}{window).navigate("http://192.168.1.10:8080/GerenciadorPampatec/");
			{
				think(1);
			}
			web.window(2, "/web:window[@index='0']"}{window).waitForPage(null);
			{
				think(1);
			}

		}
		endStep();

		beginStep("Informar Dados", 4);
		{
			web.textBox(4, "/web:window[@index='0']/web:document[@index='0']/web:form[@id='formularioDeLogin']/web:input_text[@id='formularioDeLogin:emailInput']"}{textBox).click();
			{
				think(1);
			}
			web.textBox(5, "/web:window[@index='0']/web:document[@index='0']/web:form[@id='formularioDeLogin']/web:input_text[@id='formularioDeLogin:emailInput']"}{textBox).setText("testetestezin@gmail.com");
			{
				think(1);
			}
			web.textBox(6, "/web:window[@index='0']/web:document[@index='0']/web:form[@id='formularioDeLogin']/web:input_text[@id='formularioDeLogin:emailInput']"}{textBox).pressTab();
			{
				think(1);
			}
			web.textBox(7, "/web:window[@index='0']/web:document[@index='0']/web:form[@id='formularioDeLogin']/web:input_text[@id='formularioDeLogin:emailInput']"}{textBox).setPassword("teste123");
			{
				think(1);
			}

		}
		endStep();

		beginStep("Autenticar Dados", 9);
		{
			web.button(9, "/web:window[@index='0']/web:document[@index='0']/web:form[@id='formularioDeLogin']/web:button[@id='formularioDeLogin:botaoLogin']").click();
			{
				think(1);
			}

		}
		endStep();

	}
	public void finish() throws Exception {
	}
}
